### ISSUE TITLE
Range slider doesn't result in changes

### ISSUE THREAD

**Issue by beechnut** [FortySource/forty_facets_demo#2]
In the demo, movie the range slider and clicking 'search' doesn't appear to change the results. After moving the slider and clicking the 'search' button next to it, the slider moves back to its original position, and nothing slider-related is found in the URL.

Before clicking 'search', the slider is set:

<img width="1055" alt="screen shot 2016-01-06 at 4 19 16 pm" src="https://cloud.githubusercontent.com/assets/1887182/12155092/4d2b682e-b491-11e5-9392-e3492cfacb15.png">

After clicking 'search', the slider has reset and the same number of results are returned:

<img width="1056" alt="screen shot 2016-01-06 at 4 19 26 pm" src="https://cloud.githubusercontent.com/assets/1887182/12155099/54eb9156-b491-11e5-951c-9ca6eae3a57f.png">

**Comment by axelerator** [comment]
fixed: 
https://github.com/fortytools/forty_facets_demo/commit/601e6354a825824ac42c0b66aa30579b220619ee
